import Head from "next/head";
import { useEffect } from "react";
import Scrollbar from "smooth-scrollbar";

export default function Home() {
  var options = {
    damping: 1,
  };
  useEffect(() => {
    if (typeof window !== "undefined") {
      Scrollbar.init(document.querySelector("#my-scrollbar"), options);
    }
  }, []);
  return (
    <>
      <Head>
        <title>Kiimy Medical - Skincare clinic</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <scrollbar>
        <main
          className="mx-auto mb-[420px] w-[90%] mt-24 h-[500vh] bg-slate-500"
          id="my-scrollbar"
        >
          content
        </main>
      </scrollbar>
    </>
  );
}
